update check actions

diff --git a/.github/workflows/check-actions.yaml b/.github/workflows/check-actions.yaml
--- a/.github/workflows/check-actions.yaml
+++ b/.github/workflows/check-actions.yaml
@@ -2,6 +2,11 @@ name: Check actions
 
 on:
   push:
+  pull_request:
+    branches:
+    - main
+    types:
+    - reopened
   schedule:
   - cron: "10 5 8 * *"
 permissions: {}
@@ -41,7 +46,7 @@ jobs:
     permissions:
       contents: read
     steps:
-    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
+    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
       with:
         persist-credentials: false
     - name: run actionlint
@@ -55,18 +60,35 @@ jobs:
       contents: read
       security-events: write
     steps:
-    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
+    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
       with:
         persist-credentials: false
     - name: Install the latest version of uv
-      uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 # v7.1.3
+      uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
     - name: Run zizmor 🌈
       env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         uvx zizmor --format sarif . > results.sarif
     - name: Upload SARIF file
-      uses: github/codeql-action/upload-sarif@014f16e7ab1402f30e7c3329d33797e7948572db # v4.31.3
+      uses: github/codeql-action/upload-sarif@fdbfb4d2750291e159f0156def62b853c2798ca2 # v4.31.5
       with:
         category: zizmor
         sarif_file: results.sarif
+  required-status-check:
+    name: check-actions.required-status-check
+    needs:
+    - actionlint
+    - zizmor
+    # GitHub Actions skips this job when any of the dependents fail. And skips
+    # are considered success in their weird logic. So we always run it and fail
+    # ourselves if necessary
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+    - run: echo "Use this job as the required status check of this workflow"
+    - name: Check that all jobs were successful
+      env:
+        RESULTS: ${{ toJSON(needs) }}
+      run: |
+        echo "$RESULTS" | jq --exit-status 'all(.result == "success")' || exit 1
